/*
** EPITECH PROJECT, 2019
** CPE_getnextline_bootstrap_2019
** File description:
** TODO: add description
*/

#include "my.h"
#ifndef CPE_GETNEXTLINE_BOOTSTRAP_2019_CPE_GET_NEXTLINE_BOOTSTRAP_2019_H
#define CPE_GETNEXTLINE_BOOTSTRAP_2019_CPE_GET_NEXTLINE_BOOTSTRAP_2019_H
#ifndef READ_SIZE
# define READ_SIZE 100
#endif /* !READ_SIZE */

#endif //CPE_GETNEXTLINE_BOOTSTRAP_2019_CPE_GET_NEXTLINE_BOOTSTRAP_2019_H
